import assert from 'node:assert/strict';
import { generateKeyPairSync } from 'node:crypto';
import test from 'node:test';
import { GithubSourceControlAdapter } from '../../../../../apps/api/src/source-control/adapters/github/github-source-control.adapter.js';

test('BT-032: GithubSourceControlAdapter maps provider-neutral draft review requests to GitHub draft PR API', async () => {
  let capturedUrl = '';
  let capturedInit: RequestInit | undefined;
  const adapter = new GithubSourceControlAdapter(
    {
      apiBaseUrl: 'https://api.github.test',
      token: 'github-token',
    },
    async (url, init) => {
      capturedUrl = url;
      capturedInit = init;
      return new Response(JSON.stringify({ html_url: 'https://github.com/mathis/pairdock-test/pull/7', number: 7 }), {
        status: 201,
        headers: { 'content-type': 'application/json' },
      });
    },
  );

  const result = await adapter.createDraftReviewRequest({
    projectId: '20000000-0000-4000-8000-000000000001',
    sessionId: '30000000-0000-4000-8000-000000000001',
    repoFullName: 'mathis/pairdock-test',
    sourceControlConnectionId: '40000000-0000-4000-8000-000000000001',
    providerConnectionId: 'real-installation-1',
    sourceControlAccountLogin: 'mathis',
    title: 'PairDock session 30000000',
    body: 'Generated by PairDock.',
    branchName: 'pairdock/session-30000000',
    baseBranch: 'main',
  });

  assert.equal(capturedUrl, 'https://api.github.test/repos/mathis/pairdock-test/pulls');
  assert.equal(capturedInit?.method, 'POST');
  assert.deepEqual(JSON.parse(String(capturedInit?.body)), {
    base: 'main',
    body: 'Generated by PairDock.',
    draft: true,
    head: 'pairdock/session-30000000',
    title: 'PairDock session 30000000',
  });
  assert.equal(result.reviewRequestNumber, 7);
  assert.equal(result.reviewRequestUrl, 'https://github.com/mathis/pairdock-test/pull/7');
});

test('GithubSourceControlAdapter verifies repository access through GitHub repo API', async () => {
  let capturedUrl = '';
  let capturedInit: RequestInit | undefined;
  const adapter = new GithubSourceControlAdapter(
    {
      apiBaseUrl: 'https://api.github.test',
      token: 'github-token',
    },
    async (url, init) => {
      capturedUrl = url;
      capturedInit = init;
      return new Response(JSON.stringify({ full_name: 'mathis/pairdock-test' }), {
        status: 200,
        headers: { 'content-type': 'application/json' },
      });
    },
  );

  await adapter.assertProjectAccess({
    ownerUserId: '10000000-0000-4000-8000-000000000001',
    repoFullName: 'mathis/pairdock-test',
  });

  assert.equal(capturedUrl, 'https://api.github.test/repos/mathis/pairdock-test');
  assert.equal(capturedInit?.method, 'GET');
});

test('GithubSourceControlAdapter never reports repository access without production credentials', async () => {
  const adapter = new GithubSourceControlAdapter({ apiBaseUrl: 'https://api.github.test' });

  await assert.rejects(
    adapter.assertProjectAccess({
      ownerUserId: '10000000-0000-4000-8000-000000000001',
      repoFullName: 'mathis-gala/Booster-Break',
    }),
    /GitHub credentials are required to verify repository access/,
  );
});

test('GithubSourceControlAdapter exposes TCG Collection repository for local dev fixture installations', async () => {
  const adapter = new GithubSourceControlAdapter({
    allowFixtures: true,
    apiBaseUrl: 'https://api.github.test',
  });

  const repositories = await adapter.listInstallationRepositories({
    ownerUserId: '10000000-0000-4000-8000-000000000001',
    providerConnectionId: 'test-tcg',
  });

  assert.ok(repositories.some((repository) => repository.fullName === 'mathis-gala/Booster-Break'));
});

test('GithubSourceControlAdapter creates GitHub App installation token before draft PR creation', async () => {
  const { privateKey } = generateKeyPairSync('rsa', { modulusLength: 2048 });
  const requestedUrls: string[] = [];
  const adapter = new GithubSourceControlAdapter(
    {
      apiBaseUrl: 'https://api.github.test',
      appId: '12345',
      appPrivateKey: privateKey.export({ format: 'pem', type: 'pkcs1' }).toString(),
    },
    async (url) => {
      requestedUrls.push(url);

      if (url.endsWith('/app/installations/98765/access_tokens')) {
        return new Response(JSON.stringify({ token: 'installation-token' }), {
          status: 201,
          headers: { 'content-type': 'application/json' },
        });
      }

      return new Response(JSON.stringify({ html_url: 'https://github.com/mathis/pairdock-test/pull/8', number: 8 }), {
        status: 201,
        headers: { 'content-type': 'application/json' },
      });
    },
  );

  const result = await adapter.createDraftReviewRequest({
    projectId: '20000000-0000-4000-8000-000000000001',
    sessionId: '30000000-0000-4000-8000-000000000001',
    repoFullName: 'mathis/pairdock-test',
    sourceControlConnectionId: '40000000-0000-4000-8000-000000000001',
    providerConnectionId: '98765',
    sourceControlAccountLogin: 'mathis',
    title: 'PairDock session 30000000',
    body: 'Generated by PairDock.',
    branchName: 'pairdock/session-30000000',
    baseBranch: 'main',
  });

  assert.deepEqual(requestedUrls, [
    'https://api.github.test/app/installations/98765/access_tokens',
    'https://api.github.test/repos/mathis/pairdock-test/pulls',
  ]);
  assert.equal(result.reviewRequestNumber, 8);
});
