import assert from 'node:assert/strict';
import test from 'node:test';
import { GithubSourceControlAdapter } from '../../../../../apps/api/src/source-control/adapters/github/github-source-control.adapter.js';

test('BT-032: GithubSourceControlAdapter maps provider-neutral draft review requests to GitHub draft PR API', async () => {
  let capturedUrl = '';
  let capturedInit: RequestInit | undefined;
  const adapter = new GithubSourceControlAdapter(
    {
      apiBaseUrl: 'https://api.github.test',
      token: 'github-token',
    },
    async (url, init) => {
      capturedUrl = url;
      capturedInit = init;
      return new Response(JSON.stringify({ html_url: 'https://github.com/mathis/pairdock-test/pull/7', number: 7 }), {
        status: 201,
        headers: { 'content-type': 'application/json' },
      });
    },
  );

  const result = await adapter.createDraftReviewRequest({
    projectId: '20000000-0000-4000-8000-000000000001',
    sessionId: '30000000-0000-4000-8000-000000000001',
    repoFullName: 'mathis/pairdock-test',
    sourceControlConnectionId: '40000000-0000-4000-8000-000000000001',
    providerConnectionId: 'real-installation-1',
    sourceControlAccountLogin: 'mathis',
    title: 'PairDock session 30000000',
    body: 'Generated by PairDock.',
    branchName: 'pairdock/session-30000000',
    baseBranch: 'main',
  });

  assert.equal(capturedUrl, 'https://api.github.test/repos/mathis/pairdock-test/pulls');
  assert.equal(capturedInit?.method, 'POST');
  assert.deepEqual(JSON.parse(String(capturedInit?.body)), {
    base: 'main',
    body: 'Generated by PairDock.',
    draft: true,
    head: 'pairdock/session-30000000',
    title: 'PairDock session 30000000',
  });
  assert.equal(result.reviewRequestNumber, 7);
  assert.equal(result.reviewRequestUrl, 'https://github.com/mathis/pairdock-test/pull/7');
});
